CREATE TABLE IF NOT EXISTS public.users(
  id UUID PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS public.message(
  id UUID PRIMARY KEY NOT NULL,
  id_sender UUID REFERENCES public.users(id),
  id_intended UUID REFERENCES public.users(id),
  content TEXT NOT NULL,
  date_time TIMESTAMP WITH TIME ZONE NOT NULL
);